### PR TITLE
Set to do not escape unreserved characters

### PR DESCRIPTION
**Pull request by carloshfoliveira**

### CODE REVIEW

**Comment by seocam** [comment]
Cool! Tests should be implemented on ``test_request.py`` instead of ``test_views.py``.

**Comment by carloshfoliveira** [comment]
Yeah, but we thought that since the change we made was on ```views.py```, implementing them on ```test_views.py``` made sense.

**Comment by seocam** [comment]
Nginx currently ONLY escape: ``" ", "#", "%", "?", "\x1F", "\x7F"``
Apache HTTP Server DON'T escape: ``$-_.+!*'(),:@&=/~"``

Currently we are doing to none of those. I'm working on finding a good set of chars.

**Comment by carloshfoliveira** [comment]
So, the best approach will be defining another charset instead of the unreserved ones that might cover both cases, is that it?

**Comment by seocam** [comment]
@carloshfoliveira the best approach is the one you used. ;) I'm just concerned about which strings we should consider to be safe.

**Comment by seocam** [comment]
@carloshfoliveira let's go for nginx implementation.

Instead of defining the unreserved inside the class it's better to create a constant ``QUOTE_SAFE`` just after the imports and use it on the ``quote`` function.

``QUOTE_SAFE = '<.;>\(}*+|~=-$/_:^@)[{]&\'!,"`' ``

This is basically string.punctuation without `#`, `?` and `%`.

You can also use this link as reference instead of the RFC: https://github.com/nginx/nginx/blob/nginx-1.9/src/core/ngx_string.c#L1433-L1449

**Pull request merged**
