### PR TITLE
Update tests to test Python 3.8 and Django 3.0

### PR DESCRIPTION
**Pull request by brianmay**

### CODE REVIEW

**Comment by brianmay** [comment]
Python 3.8and Django 2.2. support currently broken, see [tests](https://travis-ci.org/brianmay/django-revproxy/builds/619850226).

**Comment by brianmay** [comment]
Actually Python 3.8 is fine, just doesn't work with older Django versions. Probably need to change the tests not to test older versions of Django with Python 3.8

**Comment by brianmay** [comment]
Tests should really support Django 3.0 now too.

**Comment by vlinhart** [comment]
Hello, don't know how to really do this. So I did a fork of this pull and added the changes needed. Now the tests are run for Django 2.2, 3 and python 3.8 as well. 
https://github.com/brianmay/django-revproxy/pull/1

**Comment by brianmay** [comment]
It is a bit weird, and had me slightly confused, however, I think you did the right thing. Thanks

**Pull request merged**
