### PR TITLE
support latest urllib3 version

### PR DESCRIPTION
**Pull request by aausch**
I believe this fixes https://github.com/TracyWebTech/django-revproxy/issues/75

Note that pool.py has not been necessary since urllib3==1.6 (and minimum is now 1.12, much higher than that) --> see shazow/urllib3@9570cd2

### CODE REVIEW

**Comment by aausch** [comment]
Note that pool.py has not been necessary since urllib 1.6 (and minimum is now 1.12, much higher than that)

**Comment by aausch** [comment]
@seocam mind taking a look/merging?

**Comment by seocam** [comment]
Sorry @aausch I'm gonna work on that next week!

**Comment by seocam** [comment]
Hey @msfernandes. I've just gave you write access to the repo. Feel free to do and/or ask for modifications before merging anything.

**Comment by brianmay** [comment]
This patch breaks the tests. Yes, I know Travis tests pass, not sure why. I suspect the problem is our patching of `urllib3.PoolManager.urlopen` is not working.

**Comment by brianmay** [comment]
This change also now required:

```
diff --git a/tests/test_transformer.py b/tests/test_transformer.py
index 3ef0bbc..1db063d 100644
--- a/tests/test_transformer.py
+++ b/tests/test_transformer.py
@@ -110,6 +110,7 @@ class TransformerTest(TestCase):
         test_file = MockFile(FILE_CONTENT, 4)
         mock_file = MagicMock()
         type(mock_file).encoding = PropertyMock(return_value='utf-8')
+        type(mock_file).isclosed = MagicMock(side_effect=test_file.closed)
         type(mock_file).closed = PropertyMock(side_effect=test_file.closed)
         mock_file.read.side_effect = test_file.read
         mock_file.close.side_effect = test_file.close
@@ -137,6 +138,7 @@ class TransformerTest(TestCase):
 
         mock_file = MagicMock()
         type(mock_file).encoding = PropertyMock(return_value='utf-8')
+        type(mock_file).isclosed = MagicMock(side_effect=test_file.closed)
         type(mock_file).closed = PropertyMock(side_effect=test_file.closed)
         mock_file.read.side_effect = test_file.read
         mock_file.close.side_effect = test_file.close
```

The problem is `urllib3/util/response.py` function `is_fp_closed` now checks `obj.isclosed` before `obj.closed` and can get confused when it gets a mock object and incorrectly returns True, preventing further reads from the file.

**Comment by brianmay** [comment]
Fixed in #88.

**Pull request closed without merging**
