### PR TITLE
Move construction of proxied path to method

### PR DESCRIPTION
**Pull request by dimrozakis**
To make it easier for subclasses to modify behavior.

### CODE REVIEW

**Comment by seocam** [comment]
That method isn't actually getting the path it's only pre-processing the path before returning. Can you give me some cases where having this method would be relevant? 

Thanks!

**Comment by dimrozakis** [comment]
Hey @seocam 

So, what I was trying to do was to proxy rabbitmq's management web UI/API. Rabbitmq has a concept of vhosts, which are present in the API paths. The default rabbitmq vhost is `/`. When any query is performed concerning the `/` vhost, this is encoded in the path like this `api/queues/%2F/some-queue`.

However, what ended up being proxied was `api/queues///some-queue` which would fail.

Unfortunately, as far as I can tell, django's uri parsing happens on the unescaped data, so the path matched by the regex in the url conf would always contain `///`. In order to work around this, I defined my own subclass of `ProxyView`, and had the `dispatch` method replace `///` with `/%2f/` before calling `ProxyView`'s `dispatch` method. However, this wouldn't work, as `quote_plus` would turn it back to `///`.

By moving the preprocessing of `path` do a different method, I was able to define my own subclass of `ProxyView` which only extends `get_path`, replacing `///` with `/%2f/` after it has been quoted.

I know it isn't the cleaner solution, do you have any suggestions as to how else I could have achieved my goal of properly proxying `/%2f/`?

**Comment by dimrozakis** [comment]
>Unfortunately, as far as I can tell, django's uri parsing happens on the unescaped data, so the path matched by the regex in the url conf would always contain `///`.

https://code.djangoproject.com/ticket/15718

**Comment by seocam** [comment]
Thanks for the clarification @dimrozakis! What about calling this method `get_quoted_path`?

**Comment by dimrozakis** [comment]
@seocam sure thing. I renamed the function as suggested, rebased and pushed.

**Pull request merged**
